version: "2"

run:
  tests: true

linters:
  enable:
    - govet
    - misspell
    - errorlint

linters-settings:
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/compose-network/registry
