name: CI

on:
  pull_request:

jobs:
  build-test-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check generated chainList is up to date
        run: make check-generated

      - name: Generate (explicit)
        run: make generate

      - name: Validate chainList.toml
        run: make validate

      - name: Go Build
        run: make build

      - name: Go Test
        run: make test

      - name: Check genesis files
        run: make check-genesis

      - name: Lint
        run: make lint
